**Collections in python**

sum all the items in a list

In [1]:
item=[1,7,-10,34,2,-8]
sum = 0
for i in item:
	sum+= i
print(sum)
type(item)

26


list

get the largest number from a list


In [2]:
a=[1,7,10,3,2,8]

max = 0
for i in a:
	if i > max:
		max = i
print("Largest Number :",max)
 

Largest Number : 10


remove duplicates from a list

In [3]:
a = [1,2,3,7,2,1,5,6,4,8,5,4]
 
dup = []

for x in a:
    if x not in dup:
       
        dup.append(x)
print(dup)

[1, 2, 3, 7, 5, 6, 4, 8]


**Tuple**

Copy specific elements from one tuple to a new tuple

In [4]:
tuple1 = (11, 22, 33, 44, 55, 66)
tuple2 = tuple1[3:-1]
print(tuple2)
type(tuple1)

(44, 55)


tuple

reverse the tuple

In [5]:
tuple = (11, 22, 33, 44, 55, 66)
tuple = tuple[::-1]
print(tuple)

(66, 55, 44, 33, 22, 11)


**Sets**

program to find the missing numbers in the second set as compared to the first and vice versa

In [6]:
def missing_numbers(set_nums1, set_nums2):
    return set(set_nums1) - set(set_nums2),set(set_nums2) - set(set_nums1) 

set_nums1 = {1, 2, 3, 4, 5, 6}
set_nums2 = {3, 4, 5, 6, 7, 8}
result = missing_numbers(set_nums1, set_nums2)
print("Original sets:")
print(set_nums1)
print(set_nums2)
print("Missing numbers in the second set as compared to the first:")
print(result[0])
print("Missing numbers in the first set as compared to the second:")
print(result[1])

Original sets:
{1, 2, 3, 4, 5, 6}
{3, 4, 5, 6, 7, 8}
Missing numbers in the second set as compared to the first:
{1, 2}
Missing numbers in the first set as compared to the second:
{8, 7}


Removing All the elements from a given set

In [7]:
setc = {"Red", "Green", "Black", "White"}
print("Original set elements:")
print(setc)        
print("\nAfter removing all elements of the said set.")
setc.clear()
print(setc)
type(setc)

Original set elements:
{'White', 'Red', 'Black', 'Green'}

After removing all elements of the said set.
set()


set

**Dictionary**

concatenate the dictionaries

In [8]:
dic1={1:10, 2:20}
dic2={3:30, 4:40}
dic3={5:50,6:60}
dic4 = {}
for d in (dic1, dic2, dic3): 
  dic4.update(d)
print(dic4)

{1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}


A dictionary that contains a number (between 1 and n) in the form (x, x*x).

In [9]:
n=int(input("Input a number "))
d = dict()

for x in range(1,n+1):
    d[x]=x*x

print(d) 

Input a number 12
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144}


dictionary where the keys are numbers and the values are the square of the keys. 

In [10]:
d=dict()
for x in range(1,9):
    d[x]=x**2
print(d) 

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


deqeue

In [11]:
from collections import deque
ticket_queue = deque()

# People arrive to the queue
ticket_queue.append("Jane")
ticket_queue.append("John")
ticket_queue.append("Linda")

ticket_queue
deque(['Jane', 'John', 'Linda'])

# People bought their tickets
ticket_queue.popleft()

'Jane'

ordered dictionary

In [12]:
from collections import OrderedDict
life_stages = OrderedDict()
life_stages["childhood"] = "0-9"
life_stages["adolescence"] = "9-18"
life_stages["adulthood"] = "18-65"
life_stages["old"] = "+65"

for stage, years in life_stages.items():
      print(stage, "->", years)

childhood -> 0-9
adolescence -> 9-18
adulthood -> 18-65
old -> +65


**chainmap**

In [13]:
import collections

dictionary1 = { 'Hira' : 1, 'Hina' : 2 }  
dictionary2 = { 'Kiran' : 3, 'Komal' : 4 }  
chain_Map = collections.ChainMap(dictionary1, dictionary2)  
print(chain_Map.maps) 


[{'Hira': 1, 'Hina': 2}, {'Kiran': 3, 'Komal': 4}]


NumPy Library

In [14]:
# Python program to demonstrate
# array creation techniques
import numpy as np

# Creating array from list with type float
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print ("Array created using passed list:\n", a)

# Creating array from tuple
b = np.array((1 , 3, 2))
print ("\nArray created using passed tuple:\n", b)

# Creating a 3X4 array with all zeros
c = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", c)

# Create a constant value array of complex type
d = np.full((3, 3), 6, dtype = 'complex')
print ("\nAn array initialized with all 6s."
			"Array type is complex:\n", d)

# Create an array with random values
e = np.random.random((2, 2))
print ("\nA random array:\n", e)

# Create a sequence of integers
# from 0 to 30 with steps of 5
f = np.arange(0, 30, 5)
print ("\nA sequential array with steps of 5:\n", f)

# Create a sequence of 10 values in range 0 to 5
g = np.linspace(0, 5, 10)
print ("\nA sequential array with 10 values between"
										"0 and 5:\n", g)

# Reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4],
				[5, 2, 4, 2],
				[1, 2, 0, 1]])

newarr = arr.reshape(2, 2, 3)

print ("\nOriginal array:\n", arr)
print ("Reshaped array:\n", newarr)

# Flatten array
arr = np.array([[1, 2, 3], [4, 5, 6]])
flarr = arr.flatten()

print ("\nOriginal array:\n", arr)
print ("Fattened array:\n", flarr)


Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]

Array created using passed tuple:
 [1 3 2]

An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]

A random array:
 [[0.5820622  0.00093961]
 [0.8687931  0.60655727]]

A sequential array with steps of 5:
 [ 0  5 10 15 20 25]

A sequential array with 10 values between0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]

Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


Indexing of Array

In [15]:
import numpy as np
 
# An exemplar array
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
 
# Slicing array
temp = arr[:2, ::2]
print (temp)
 
# Integer array indexing example
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print (temp)
 
# boolean array indexing example
cond = arr > 0 # cond is a boolean array
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)

[[-1.  0.]
 [ 4.  6.]]
[4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


Operations on array

In [16]:
import numpy as np
 
a = np.array([1, 2, 5, 3])
 
# add 1 to every element
print ("Adding 1 to every element:", a+1)
 
# subtract 3 from each element
print ("Subtracting 3 from each element:", a-3)
 
# multiply each element by 10
print ("Multiplying each element by 10:", a*10)
 
# square each element
print ("Squaring each element:", a**2)
 
# modify existing array
a *= 2
print ("Doubled each element of original array:", a)
 
# transpose of array
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
 
print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)

Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


**Pandas**

In [17]:
import pandas as pd
data1=pd.Series([1,4,2,7,8],index=['a','b','c', 'd','e'])
data2=pd.Series([3,6,1,0,8],index=['a','b','c', 'd','e'])
print("data1:\n", data1)
print()
print("data2:\n", data2)
print()
df=data1.add(data2)
print("data1+data2:\n",df)

data1:
 a    1
b    4
c    2
d    7
e    8
dtype: int64

data2:
 a    3
b    6
c    1
d    0
e    8
dtype: int64

data1+data2:
 a     4
b    10
c     3
d     7
e    16
dtype: int64


In [18]:
import pandas as pd
data1=pd.Series([1,4,2,7,8],index=['a','b','c', 'd','e'])
print("Before Conversion:\n")
print(data1)
print()
print("After Conversion:\n")
data2=data1.astype(float)
print("data1:\n", data2)

Before Conversion:

a    1
b    4
c    2
d    7
e    8
dtype: int64

After Conversion:

data1:
 a    1.0
b    4.0
c    2.0
d    7.0
e    8.0
dtype: float64


In [19]:
import pandas as pd
data = pd.read_csv('https://raw.githubusercontent.com/jbrownlee/Datasets/master/daily-total-female-births.csv')
print(type(data))
print(data)
print(data.head(6))
df=data["Births"]
print("Before:\n",df)
print()
print("After:\n",df.astype(float))

<class 'pandas.core.frame.DataFrame'>
           Date  Births
0    1959-01-01      35
1    1959-01-02      32
2    1959-01-03      30
3    1959-01-04      31
4    1959-01-05      44
..          ...     ...
360  1959-12-27      37
361  1959-12-28      52
362  1959-12-29      48
363  1959-12-30      55
364  1959-12-31      50

[365 rows x 2 columns]
         Date  Births
0  1959-01-01      35
1  1959-01-02      32
2  1959-01-03      30
3  1959-01-04      31
4  1959-01-05      44
5  1959-01-06      29
Before:
 0      35
1      32
2      30
3      31
4      44
       ..
360    37
361    52
362    48
363    55
364    50
Name: Births, Length: 365, dtype: int64

After:
 0      35.0
1      32.0
2      30.0
3      31.0
4      44.0
       ... 
360    37.0
361    52.0
362    48.0
363    55.0
364    50.0
Name: Births, Length: 365, dtype: float64


In [20]:
import json
json_obj =  '{ "Name":"AHMED ALI ANSARI", "Semester":"VI", "ID":1402 }'
python_obj = json.loads(json_obj)
print("\nJSON data:")
print(python_obj)
print("\nName: ",python_obj["Name"])
print("Semester: ",python_obj["Semester"])
print("ID: ",python_obj["ID"]) 



JSON data:
{'Name': 'AHMED ALI ANSARI', 'Semester': 'VI', 'ID': 1402}

Name:  AHMED ALI ANSARI
Semester:  VI
ID:  1402


In [26]:
import json
python_obj =  { "Name":"AHMED ALI ANSARI", "Semester":"VI", "ID":1402 }
jasobj = json.dumps(python_obj)
print("\nJSON data:")
print(jasobj)

with open('jasobj.json', 'w') as f:
  print("The json file is created")


JSON data:
{"Name": "AHMED ALI ANSARI", "Semester": "VI", "ID": 1402}
The json file is created


FileNotFoundError: [Errno 2] No such file or directory: 'data.json'

In [36]:
import json

with open('jasobj.json', 'r') as j:
     contents = json.loads(j.read())
    #data = json.load(f)

for info in contents['Name']:
    del state['AHMED ALI ANSARI']

with open('jasobj.json', 'w') as f:
    json.dump(state_data, f, indent=2)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)